echo "Starting..."
python write_random_boards.py "4" "20" "35"
echo "boards written"
python write_random_results_with_bot.py "4" "20" "35"
echo "Board Results Written"
python learn_from_list_of_games.py "20" "35"
echo "Learneded on the first one.."
echo "Starting..."
python write_random_boards.py "4" "10" "19"
echo "boards written"
python write_random_results_with_bot.py "4" "10" "19"
echo "Board Results Written"
python learn_from_list_of_games.py "10" "19"
echo "Learneded on the second one.."
echo "Starting..."
python write_random_boards.py "4" "0" "9"
echo "boards written"
python write_random_results_with_bot.py "4" "0" "9"
echo "Board Results Written"
python learn_from_list_of_games.py "0" "9"
echo "Learned the last one."
echo "DONE!"